### ISSUE TITLE
Download link does not work

### ISSUE THREAD

**Issue by krambriw** [Lapland-UAS-Tequ/tequ-jetson-nodered-tensorflow#1]
Hello, this link does not work, I try to do this on my Jetson Nano. Can I ask you to repair?
Best regards, Walter

wget https://jetson-nodered-files.s3.eu.cloud-object-storage.appdomain.cloud/libtensorflow-2.4-jetson-5.3-7.2-no-tensorrt.tar.gz

**Comment by juhaautioniemi** [comment]
Hi, thanks for noticing this and it should be fixed now

**Comment by krambriw** [comment]
Sorry, does not

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Resource>/jetson-nodered-files/libtensorflow-2.4-jetson-5.3-7.2-no-tensorrt.tar.gz</Resource>
<RequestId>a7006534-61dc-4b38-8704-4df80f8499fe</RequestId>
<httpStatusCode>404</httpStatusCode>
</Error>

**Comment by juhaautioniemi** [comment]
Did you refresh the page and look up that same line again in repo. This link was written incorrectly and is now fixed.

**Comment by krambriw** [comment]
Ohh, thank you very much, works perfect now!!
It will be interesting to test your setup here, I have been using YOLO v4 with GPU support for several years on a Jetson Nano running in a Python script, interfaced with Node-RED via MQTT
Always interesting to try other alternatives
Best regards, Walter

![image](https://github.com/Lapland-UAS-Tequ/tequ-jetson-nodered-tensorflow/assets/20238676/099df2de-19bd-4de4-b942-af8d1c532f1c)
